/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{svelte,ts}'],
  theme: {
    extend: {
      fontFamily: {
        sans: [
          'Pretendard',
          '-apple-system',
          'BlinkMacSystemFont',
          'system-ui',
          'Segoe UI',
          'Roboto',
          'sans-serif',
        ],
      },
      colors: {
        /* Toss-native tokens */
        'toss-blue': '#3182F6',
        'toss-blue-hover': '#1B64DA',
        'toss-blue-light': '#E8F2FE',
        'toss-bg': '#F9FAFB',
        'toss-bg-soft': '#F2F4F6',
        'toss-surface': '#FFFFFF',
        'toss-text-strong': '#191F28',
        'toss-text': '#4E5968',
        'toss-text-weak': '#8B95A1',
        'toss-text-disabled': '#B0B8C1',
        'toss-line': '#F2F4F6',
        'toss-line-strong': '#E5E8EB',
        'toss-error': '#F04452',
        'toss-success': '#00C471',

        /* Backwards-compat aliases for existing MD3 class names */
        primary: 'var(--md-sys-color-primary)',
        'on-primary': 'var(--md-sys-color-on-primary)',
        'primary-container': 'var(--md-sys-color-primary-container)',
        'on-primary-container': 'var(--md-sys-color-on-primary-container)',
        'secondary-container': 'var(--md-sys-color-secondary-container)',
        'on-secondary-container': 'var(--md-sys-color-on-secondary-container)',
        surface: 'var(--md-sys-color-surface)',
        'surface-container': 'var(--md-sys-color-surface-container)',
        'surface-container-high': 'var(--md-sys-color-surface-container-high)',
        'surface-container-highest': 'var(--md-sys-color-surface-container-highest)',
        'on-surface': 'var(--md-sys-color-on-surface)',
        'on-surface-variant': 'var(--md-sys-color-on-surface-variant)',
        outline: 'var(--md-sys-color-outline)',
        'outline-variant': 'var(--md-sys-color-outline-variant)',
        'md-error': 'var(--md-sys-color-error)',
        'on-md-error': 'var(--md-sys-color-on-error)',
      },
      borderRadius: {
        'md-sm': '10px',
        'md-md': '14px',
        'md-lg': '18px',
        'md-xl': '20px',
        'toss-chip': '8px',
        'toss-btn': '12px',
        'toss-card': '18px',
        'toss-xl': '24px',
      },
      boxShadow: {
        'md-1': '0 1px 3px rgba(0,0,0,0.04)',
        'md-2': '0 2px 8px rgba(0,0,0,0.06)',
        'toss-card': '0 1px 3px rgba(0,0,0,0.04)',
      },
    },
  },
  plugins: [],
};
